# Generated by Django 4.2.7 on 2026-08-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('SCI-FI', 'Sci-Fi'), ('THRILLER', 'Thriller'), ('ANIMATION', 'Animation'), ('DOCUMENTARY', 'Documentary'), ('FANTASY', 'Fantasy'), ('MYSTERY', 'Mystery')], max_length=20)),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('language', models.CharField(max_length=50)),
                ('poster_url', models.URLField(max_length=500)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director', models.CharField(blank=True, help_text='Movie director', max_length=200)),
                ('cast', models.TextField(blank=True, help_text='Main cast members, comma separated')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('age_rating', models.CharField(blank=True, help_text='e.g., PG-13, R, U/A', max_length=10)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('seat_layout', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('total_screens', models.IntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Theater',
                'verbose_name_plural': 'Theaters',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.CharField(choices=[('MORNING', 'Morning (10:00 AM)'), ('AFTERNOON', 'Afternoon (1:00 PM)'), ('EVENING', 'Evening (4:00 PM)'), ('NIGHT', 'Night (7:00 PM)'), ('LATE_NIGHT', 'Late Night (10:00 PM)')], max_length=20)),
                ('show_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField()),
                ('booked_seats', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.screen')),
            ],
            options={
                'ordering': ['show_date', 'show_time'],
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='movies.theater'),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('theater', 'screen_number')},
        ),
    ]
